{
 "title": "Docapi Dashboard",
 "tags": [
  "go",
  "fiber",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latency P50 / P95 / P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))) * 1000",
     "legendFormat": "Latency (ms)"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{}[5m]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Resident Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100"
    }
   ]
  },
  {
   "title": "Heap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"docapi\"} |= `` | json"
    }
   ]
  }
 ]
}